# Simple case - single database
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: orders-api
  namespace: team-alpha
spec:
  database:
    name: orders-db
  privileges: readwrite
---
# Admin user for migrations with password rotation
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: orders-migrations
  namespace: team-alpha
spec:
  database:
    name: orders-db
  username: orders_admin
  privileges: admin
  password:
    length: 32
  rotation:
    days: 30
  deletionPolicy: Delete
---
# Readonly user with connection limit
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: orders-readonly
  namespace: team-alpha
spec:
  database:
    name: orders-db
  privileges: readonly
  connectionLimit: 5
---
# Multiple databases - one user, different privileges per database
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: airbyte-service
  namespace: platform
spec:
  databases:
    - name: airbyte-db
      privileges: readwrite
    - name: temporal-db
      privileges: readwrite
    - name: temporal-visibility-db
      privileges: readonly
  privileges: readonly  # default for databases without explicit privileges
  password:
    length: 24
---
# Multiple databases with separate secret per database
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: multi-db-service
  namespace: platform
spec:
  databases:
    - name: db1
    - name: db2
    - name: db3
  privileges: readwrite
  secretGeneration: perDatabase  # creates 3 secrets with same password, different database field
  secret:
    template: POSTGRES
---
# User with Retain policy - user stays in PostgreSQL after resource deletion
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: shared-service
  namespace: team-alpha
spec:
  database:
    name: payments-db
  privileges: readwrite
  deletionPolicy: Retain
---
# User with custom secret name and DATABASE template
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: api-user
  namespace: team-alpha
spec:
  database:
    name: orders-db
  privileges: readwrite
  secret:
    name: api-db-credentials
    template: DATABASE
---
# User with POSTGRES template (for standard PostgreSQL env vars)
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: postgres-app
  namespace: team-alpha
spec:
  database:
    name: orders-db
  privileges: readwrite
  secret:
    template: POSTGRES
---
# User with fully custom secret keys (for legacy app compatibility)
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: legacy-connector
  namespace: team-alpha
spec:
  database:
    name: orders-db
  privileges: readonly
  secret:
    name: postgres-config
    template: custom
    keys:
      host: PGHOST
      port: PGPORT
      database: PGDATABASE
      user: PGUSER
      password: PGPASSWORD
---
# User with onConflict: Adopt - take over existing secret
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: adopt-user
  namespace: team-alpha
spec:
  database:
    name: orders-db
  privileges: readwrite
  secret:
    name: orphaned-secret
    onConflict: Adopt
---
# User with onConflict: Merge - add credentials to existing secret
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: merge-user
  namespace: team-alpha
spec:
  database:
    name: orders-db
  privileges: readwrite
  secret:
    name: app-config
    template: raw
    onConflict: Merge
---
# Cross-namespace database reference
apiVersion: dbtether.io/v1alpha1
kind: DatabaseUser
metadata:
  name: analytics-reader
  namespace: analytics
spec:
  database:
    name: main-db
    namespace: production
  privileges: readonly
